### ISSUE TITLE
Expose simulation parameters

### ISSUE THREAD

**Issue by werediver** [dominicdoty/lunar_lander#2]
It would also help a lot, if the simulation parameters are documented (or exposed through an API), such as free fall acceleration, allowed speed at touchdown, etc.

It may also be nice to run the simulation based on time, not frames (so that the free fall acceleration is defines per unit of time, not per frame, etc.), but that may be a design choice, of course.

(and thanks again for sharing this fun simulator 🙂)

**Comment by dominicdoty** [comment]
Thanks! I'm glad you like it.

I went ahead and added a comment to the default editor contents explaining some of the parameters used in simulation. I've chosen to leave the tracking of those values (e.g. fuel level) up to the user since I feel like that keeps it fun.

I do agree that time should have been absolute instead of frame based, and if I were starting from scratch I'd definitely go that way. I don't think I take the frame rate into account in the simulation as it would make your control loop phase margin change if you ran the same autopilot on two different systems. Unfortunately this also means gravity just slows down on lower frame rate devices which is also weird.

All this to say: I wish I had done what you suggest but it might be too late to change it now :face_with_diagonal_mouth: 

I'm gonna go ahead and close this one for now though if you have no objections!
